### ISSUE TITLE
Downloaded Videos

### ISSUE THREAD

**Issue by dipta007** [katesanders9/multiVENT#2]
Can we get all the downloaded videos, as some are age/location-restricted?

If not, can you tell me which Python library you used to download Twitter videos?

**Comment by katesanders9** [comment]
Hi, thanks for your interest in the dataset! We're currently working out a more robust data distribution approach, which will be updated on the repository soon. For now, we don't have an official method for downloading restricted videos and Twitter content, due to continual changes to their respective video hosting platforms.
